// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, created_at
`

type CreateAdminParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.ID, arg.Email, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, created_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, created_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
