// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO admin_audit_log (id, admin_id, event, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	ID        uuid.UUID  `json:"id"`
	AdminID   *uuid.UUID `json:"admin_id"`
	Event     string     `json:"event"`
	Ip        *string    `json:"ip"`
	UserAgent *string    `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.AdminID,
		arg.Event,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}
