// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leads.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const createLead = `-- name: CreateLead :one
INSERT INTO leads (id, name, email, message, locale, source_page, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, email, message, locale, source_page, ip, user_agent, created_at
`

type CreateLeadParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Message    string      `json:"message"`
	Locale     string      `json:"locale"`
	SourcePage *string     `json:"source_page"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Message,
		arg.Locale,
		arg.SourcePage,
		arg.Ip,
		arg.UserAgent,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.Locale,
		&i.SourcePage,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT id, name, email, message, locale, source_page, ip, user_agent, created_at FROM leads
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListLeadsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// The id tiebreaker is not decoration. ORDER BY created_at alone is not a total order, and two
// rows can share a created_at under concurrent inserts, at which point LIMIT/OFFSET paging can
// show the same lead on two pages or skip one entirely. Postgres is free to return tied rows in
// any order between queries.
func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.Locale,
			&i.SourcePage,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
