// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package sqlc

import (
	"context"
	"time"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts WHERE email = $1
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, clearLoginAttempts, email)
	return err
}

const extendLoginLock = `-- name: ExtendLoginLock :exec
UPDATE login_attempts
SET locked_until = GREATEST(COALESCE(locked_until, $1), $1)
WHERE email = $2
`

type ExtendLoginLockParams struct {
	LockedUntil *time.Time `json:"locked_until"`
	Email       string     `json:"email"`
}

// Only ever extends. Concurrent failures compute different windows from different counts, and the
// longest one is the one that should stand: taking the last writer instead would let a request
// that incremented to 5 shorten a lock a request that incremented to 20 had already set.
func (q *Queries) ExtendLoginLock(ctx context.Context, arg ExtendLoginLockParams) error {
	_, err := q.db.Exec(ctx, extendLoginLock, arg.LockedUntil, arg.Email)
	return err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT email, failed_count, locked_until FROM login_attempts WHERE email = $1
`

func (q *Queries) GetLoginAttempt(ctx context.Context, email string) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, email)
	var i LoginAttempt
	err := row.Scan(&i.Email, &i.FailedCount, &i.LockedUntil)
	return i, err
}

const pruneLoginAttempts = `-- name: PruneLoginAttempts :exec
DELETE FROM login_attempts WHERE locked_until IS NOT NULL AND locked_until < now() - interval '1 day'
`

// Rows whose lock lapsed more than a day ago cannot affect any future decision: the backoff curve
// reads failed_count, and a count that old is not evidence of anything current.
func (q *Queries) PruneLoginAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneLoginAttempts)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO login_attempts (email, failed_count)
VALUES ($1, 1)
ON CONFLICT (email) DO UPDATE
    SET failed_count = login_attempts.failed_count + 1
RETURNING email, failed_count, locked_until
`

// One statement so two concurrent failures cannot both read 2 and both write 3. It touches only
// the count: the returned row carries the post-increment value, which is the number the caller
// feeds to the backoff curve, and the lock itself is written by ExtendLoginLock afterwards. The
// curve stays in Go because it is policy, not storage.
func (q *Queries) RecordLoginFailure(ctx context.Context, email string) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, email)
	var i LoginAttempt
	err := row.Scan(&i.Email, &i.FailedCount, &i.LockedUntil)
	return i, err
}
