// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_attempts.sql

package sqlc

import (
	"context"
	"time"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts WHERE email = $1 AND ip = $2
`

type ClearLoginAttemptsParams struct {
	Email string `json:"email"`
	Ip    string `json:"ip"`
}

// Clears only this pair, so the admin's sign-in does not reset an attacker's backoff.
func (q *Queries) ClearLoginAttempts(ctx context.Context, arg ClearLoginAttemptsParams) error {
	_, err := q.db.Exec(ctx, clearLoginAttempts, arg.Email, arg.Ip)
	return err
}

const extendLoginLock = `-- name: ExtendLoginLock :exec
UPDATE login_attempts
SET locked_until = GREATEST(COALESCE(locked_until, $1), $1)
WHERE email = $2 AND ip = $3
`

type ExtendLoginLockParams struct {
	LockedUntil *time.Time `json:"locked_until"`
	Email       string     `json:"email"`
	Ip          string     `json:"ip"`
}

// Only ever extends, so a concurrent request with a lower count cannot shorten a longer lock.
func (q *Queries) ExtendLoginLock(ctx context.Context, arg ExtendLoginLockParams) error {
	_, err := q.db.Exec(ctx, extendLoginLock, arg.LockedUntil, arg.Email, arg.Ip)
	return err
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT email, failed_count, locked_until, last_failure_at, ip FROM login_attempts WHERE email = $1 AND ip = $2
`

type GetLoginAttemptParams struct {
	Email string `json:"email"`
	Ip    string `json:"ip"`
}

func (q *Queries) GetLoginAttempt(ctx context.Context, arg GetLoginAttemptParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, arg.Email, arg.Ip)
	var i LoginAttempt
	err := row.Scan(
		&i.Email,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailureAt,
		&i.Ip,
	)
	return i, err
}

const pruneLoginAttempts = `-- name: PruneLoginAttempts :exec
DELETE FROM login_attempts
WHERE last_failure_at < $1
  AND (locked_until IS NULL OR locked_until < now())
`

// Prunes by age, so rows that never reached a lock are removed too. A row still inside its lock
// window is kept.
func (q *Queries) PruneLoginAttempts(ctx context.Context, staleBefore time.Time) error {
	_, err := q.db.Exec(ctx, pruneLoginAttempts, staleBefore)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
INSERT INTO login_attempts (email, ip, failed_count)
VALUES ($1, $2, 1)
ON CONFLICT (email, ip) DO UPDATE
    SET failed_count = CASE
            WHEN login_attempts.last_failure_at < $3 THEN 1
            ELSE login_attempts.failed_count + 1
        END,
        last_failure_at = now()
RETURNING email, failed_count, locked_until, last_failure_at, ip
`

type RecordLoginFailureParams struct {
	Email       string    `json:"email"`
	Ip          string    `json:"ip"`
	DecayBefore time.Time `json:"decay_before"`
}

// One statement, so two concurrent failures cannot both read 2 and write 3. The caller feeds the
// returned count to the backoff curve. A failure older than decay_before resets the count to one.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (LoginAttempt, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.Email, arg.Ip, arg.DecayBefore)
	var i LoginAttempt
	err := row.Scan(
		&i.Email,
		&i.FailedCount,
		&i.LockedUntil,
		&i.LastFailureAt,
		&i.Ip,
	)
	return i, err
}
