// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Lead struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Message    string      `json:"message"`
	Locale     string      `json:"locale"`
	SourcePage *string     `json:"source_page"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}
