// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AdminAuditLog struct {
	ID        uuid.UUID  `json:"id"`
	AdminID   *uuid.UUID `json:"admin_id"`
	Event     string     `json:"event"`
	Ip        *string    `json:"ip"`
	UserAgent *string    `json:"user_agent"`
	CreatedAt time.Time  `json:"created_at"`
}

type AdminUser struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Lead struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
	Message    string      `json:"message"`
	Locale     string      `json:"locale"`
	SourcePage *string     `json:"source_page"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	CreatedAt  time.Time   `json:"created_at"`
}

type LoginAttempt struct {
	Email       string     `json:"email"`
	FailedCount int32      `json:"failed_count"`
	LockedUntil *time.Time `json:"locked_until"`
}

type RefreshToken struct {
	Jti       uuid.UUID  `json:"jti"`
	AdminID   uuid.UUID  `json:"admin_id"`
	FamilyID  uuid.UUID  `json:"family_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
}
