// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (jti, admin_id, family_id, expires_at, family_expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	Jti             uuid.UUID `json:"jti"`
	AdminID         uuid.UUID `json:"admin_id"`
	FamilyID        uuid.UUID `json:"family_id"`
	ExpiresAt       time.Time `json:"expires_at"`
	FamilyExpiresAt time.Time `json:"family_expires_at"`
}

// family_expires_at is set at login and copied forward by every rotation. The caller clamps
// expires_at to it.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Jti,
		arg.AdminID,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.FamilyExpiresAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE admin_id = $1 AND expires_at < now()
`

// Runs on each login. expires_at is clamped to family_expires_at, so it covers both deadlines.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, adminID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, admin_id, family_id, expires_at, revoked_at, family_expires_at, replaced_by FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.AdminID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.FamilyExpiresAt,
		&i.ReplacedBy,
	)
	return i, err
}

const lockTokenFamily = `-- name: LockTokenFamily :exec
SELECT pg_advisory_xact_lock(hashtextextended(($1::uuid)::text, 0))
`

// Serializes every writer on one token family until the transaction ends. Row locks are not
// enough: a family revoke cannot see a successor row inserted after its scan began.
func (q *Queries) LockTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockTokenFamily, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = now(), replaced_by = $1
WHERE jti = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ReplacedBy *uuid.UUID `json:"replaced_by"`
	Jti        uuid.UUID  `json:"jti"`
}

// The caller must read the row count. Zero means another request spent this token first. A
// SELECT beforehand cannot tell, because both requests can pass it before either writes.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.ReplacedBy, arg.Jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

// Must run under LockTokenFamily in the same transaction.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
