// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (jti, admin_id, family_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	Jti       uuid.UUID `json:"jti"`
	AdminID   uuid.UUID `json:"admin_id"`
	FamilyID  uuid.UUID `json:"family_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.Jti,
		arg.AdminID,
		arg.FamilyID,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE admin_id = $1 AND expires_at < now()
`

// Housekeeping, run on each login for the admin logging in. That keeps the table bounded with no
// scheduled job: a row can only outlive its expiry until its owner next signs in.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, adminID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, admin_id, family_id, expires_at, revoked_at FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, jti)
	var i RefreshToken
	err := row.Scan(
		&i.Jti,
		&i.AdminID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens SET revoked_at = now() WHERE jti = $1 AND revoked_at IS NULL
`

// Returns rows affected, and the caller must read it. The WHERE clause carries revoked_at IS NULL,
// so this single statement is both the check and the write: under READ COMMITTED the second of two
// concurrent updates to the same row blocks on the row lock, then re-evaluates its predicate
// against the committed version, finds revoked_at already set, and matches nothing. Zero rows
// therefore means another request spent this token first, which is the same event as presenting an
// already-revoked one. Reading the count is what makes spending a token atomic; a preceding SELECT
// cannot, because two callers can both pass it before either writes.
func (q *Queries) RevokeRefreshToken(ctx context.Context, jti uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
